#+TITLE: viz's Emacs configuration
I use straight.el instead of package.el because it is a lot more convenient to use
than using package.el and a mix of ~load~.

Screenshot - http://0x0.st/iWib.png
* Conventions used
| Functions                       | vz/asdf                |
| Functions that return a boolean | vz/verb?               |
| Variables                       | vz/asdf                |
| Minor mode                      | vz/asdf-minor-mode     |
| Minor mode map                  | vz/asdf-minor-mode-map |
* On org-mode
I currently use org-mode to take notes for school but plan to use it for agenda
and schedules.
* TODO Consider giving up evil?
I think default Emacs bindings make sense but the reason why I don't use it
is because I don't find it comfortable to press Ctrl, even if I map it to Right Alt.
(And no, I don't want to map it to Caps Lock).

Also, I think Emacs' editing methodologies makes sense, in fact, I think something
like ~expand-region~ and ~avy~ jump functions is a lot more intuitive.

The reason why I don't use Emacs default binds is because I like my editor to
be modal -- vi-like or acme-like. Acme-like in the sense that mouse does all the things
i.e., /normal mode/ and keyboard does only input i.e., /insert mode/.

So maybe it might be worth it to make my modal configuration based around
~expand-region~ and ~avy~ using ~modalka~.

The main thing that I would miss is probably ~evil-repeat~ and ~evil-repeat-find-char~.
But the latter should not be a problem anymore if I use ~avy~ for /every/ text movement.

Some of this is inspired by [[Mike Zamansky's video][https://www.youtube.com/watch?v=0M6erlK57go]] on Emacs vs Vi
