(set-face-attribute 'default nil :background vz:color0   :foreground vz:color7)
(set-face-attribute 'font-lock-builtin-face nil :foreground vz:color7)
(set-face-attribute 'font-lock-comment-face nil :foreground vz:color8)
(set-face-attribute 'font-lock-negation-char-face nil :foreground vz:color0)
(set-face-attribute 'font-lock-constant-face nil :foreground vz:color2)
(set-face-attribute 'font-lock-doc-face nil :foreground vz:color8)
(set-face-attribute 'font-lock-function-name-face nil :foreground vz:color5)
(set-face-attribute 'font-lock-keyword-face nil :foreground vz:color1)
(set-face-attribute 'font-lock-string-face nil :foreground vz:color5)
(set-face-attribute 'font-lock-type-face nil :foreground vz:color3)
(set-face-attribute 'font-lock-variable-name-face nil :foreground vz:color4)
(set-face-attribute 'font-lock-warning-face nil :foreground vz:color3)
(set-face-attribute 'region nil :background vz:color8 :foreground vz:color15)
(set-face-attribute 'highlight nil :background vz:color8 :foreground vz:color15)
(set-face-attribute 'show-paren-match nil :background vz:color8 :foreground vz:color15)
(set-face-attribute 'show-paren-match-expression nil :background vz:color8 :foreground vz:color15)
(set-face-attribute 'show-paren-mismatch nil :background vz:color1 :foreground vz:color15)
(set-face-attribute 'cursor nil :background vz:color8 :foreground vz:color8)
(set-face-attribute 'isearch nil :background vz:color8 :foreground vz:color15)
(set-face-attribute 'vertical-border nil :foreground vz:color15)
(set-face-attribute 'minibuffer-prompt nil :foreground vz:color5)
(set-face-attribute 'link nil :foreground vz:color5)
(set-face-attribute 'warning nil :foreground vz:color3)
(set-face-attribute 'trailing-whitespace nil :background vz:color8)
;;(set-face-attribute 'org-code nil :foreground vz:color8)
;;(set-face-attribute 'org-hide nil :foreground vz:color8)
;;(set-face-attribute 'org-level-1 nil :foreground vz:color1)
;;(set-face-attribute 'org-level-2 nil :foreground vz:color2)
;;(set-face-attribute 'org-level-3 nil :foreground vz:color3)
;;(set-face-attribute 'org-level-4 nil :foreground vz:color4)
;;(set-face-attribute 'org-date nil :foreground vz:color10)
;;(set-face-attribute 'org-footnote nil :foreground vz:color12)
;;(set-face-attribute 'org-link nil :foreground vz:color5)
;;(set-face-attribute 'org-special-keyword nil:foreground vz:color10)
;;(set-face-attribute 'org-block nil :foreground vz:color8)
;;(set-face-attribute 'org-quote nil :foreground vz:color12)
;;(set-face-attribute 'org-verse nil :foreground vz:color13)
;;(set-face-attribute 'org-todo nil :foreground vz:color1)
;;(set-face-attribute 'org-done nil :foreground vz:color2)
;;(set-face-attribute 'org-warning nil:foreground vz:color3)
;;(set-face-attribute 'org-agenda-structure nil:foreground vz:color0)
;;(set-face-attribute 'org-agenda-date nil :foreground vz:color15)
;;(set-face-attribute 'org-agenda-date-weekend nil:foreground vz:color15)
;;(set-face-attribute 'org-agenda-date-today nil:foreground vz:color8)
;;(set-face-attribute 'org-agenda-done nil :foreground vz:color2)
;;(set-face-attribute 'org-scheduled nil :foreground vz:color8)
;;(set-face-attribute 'org-scheduled-today nil :foreground vz:color1)
;;(set-face-attribute 'org-ellipsis nil :foreground vz:color10)
;;(set-face-attribute 'org-verbatim nil:foreground vz:color12)
;;(set-face-attribute 'org-sexp-date nil:foreground vz:color2)
;;(set-face-attribute 'font-latex-bold-face nil :foreground vz:color8)
;;(set-face-attribute 'font-latex-italic-face nil :foreground vz:color8)
;;(set-face-attribute 'font-latex-string-face nil:foreground vz:color7)
;;(set-face-attribute 'font-latex-match-reference-keywords nil :background vz:color8 :foreground vz:color15)
;;(set-face-attribute 'font-latex-match-variable-keywords nil :background vz:color8 :foreground vz:color15)
(set-face-attribute 'rainbow-delimiters-base-face nil :foreground vz:color7)
(set-face-attribute 'rainbow-delimiters-depth-1-face nil :foreground vz:color1)
(set-face-attribute 'rainbow-delimiters-depth-2-face nil :foreground vz:color2)
(set-face-attribute 'rainbow-delimiters-depth-3-face nil :foreground vz:color3)
(set-face-attribute 'rainbow-delimiters-depth-4-face nil :foreground vz:color4)
(set-face-attribute 'rainbow-delimiters-depth-5-face nil :foreground vz:color5)
(set-face-attribute 'rainbow-delimiters-depth-6-face nil :foreground vz:color6)
(set-face-attribute 'rainbow-delimiters-depth-7-face nil :foreground vz:color7)
(set-face-attribute 'rainbow-delimiters-depth-8-face nil :foreground vz:color8)
(set-face-attribute 'rainbow-delimiters-unmatched-face nil :background vz:color1 :foreground vz:color15)
(set-face-attribute 'lazy-highlight nil :background vz:color8 :foreground vz:color13)
